/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CanvasDragZoom: typeof import('./src/components/CanvasDragZoom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyResult: typeof import('./src/components/emptyResult.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImgCanvas: typeof import('./src/components/imgCanvas.vue')['default']
    LightCornerBox: typeof import('./src/components/LightCornerBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperGroup: typeof import('./src/components/swiperGroup.vue')['default']
    TestSwiper: typeof import('./src/components/testSwiper.vue')['default']
  }
}
