import { ref } from "vue";
export default function () {
  let list = [
    //KR-XJ03
    {
      devicesTypeValue: "0",
      actionTypeOption: [
        {
          actionTypeValue: "zhuapai",
          actionTypeLabel: "可见光抓拍",
          actionTypeIcon: "tubiao_kejianguangzhuapai-42",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "hongwai",
          actionTypeLabel: "红外测温",
          actionTypeIcon: "redtemp",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "huanjing",
          actionTypeLabel: "环境监测",
          actionTypeIcon: "tubiao_huanjingjiance",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
          },
        },
        {
          actionTypeValue: "biaoji",
          actionTypeLabel: "表计识别",
          actionTypeIcon: "kejianguangshibie",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "lianpai",
          actionTypeLabel: "连拍",
          actionTypeIcon: "tubiao_hengxianglianpai-40",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "shouwang",
          actionTypeLabel: "守望",
          actionTypeIcon: "shouwang",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
      ],
    },
    //KR-XJ05
    {
      devicesTypeValue: "1",
      actionTypeOption: [
        {
          actionTypeValue: "zhuapai",
          actionTypeLabel: "可见光抓拍",
          actionTypeIcon: "tubiao_kejianguangzhuapai-42",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "hongwai",
          actionTypeLabel: "红外测温",
          actionTypeIcon: "redtemp",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "huanjing",
          actionTypeLabel: "环境监测",
          actionTypeIcon: "tubiao_huanjingjiance",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
          },
        },
        {
          actionTypeValue: "biaoji",
          actionTypeLabel: "表计识别",
          actionTypeIcon: "kejianguangshibie",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "lianpai",
          actionTypeLabel: "连拍",
          actionTypeIcon: "tubiao_hengxianglianpai-40",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "shouwang",
          actionTypeLabel: "守望",
          actionTypeIcon: "shouwang",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
      ],
    },
    //KR-XJ04
    {
      devicesTypeValue: "2",
      actionTypeOption: [
        {
          actionTypeValue: "zhuapai",
          actionTypeLabel: "可见光抓拍",
          actionTypeIcon: "tubiao_kejianguangzhuapai-42",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            jingque: true,
            jigao: true,
            jichao: true,
            xjjiaodu: true,
            bgjiaodu: true,
            bgliangdu: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "hongwai",
          actionTypeLabel: "红外测温",
          actionTypeIcon: "redtemp",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            jingque: true,
            jigao: true,
            jichao: true,
            xjjiaodu: true,
            bgjiaodu: true,
            bgliangdu: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "huanjing",
          actionTypeLabel: "环境监测",
          actionTypeIcon: "tubiao_huanjingjiance",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            jingque: true,
          },
        },
        {
          actionTypeValue: "biaoji",
          actionTypeLabel: "表计识别",
          actionTypeIcon: "kejianguangshibie",
          canUsePresetPoint: false,
          locationPoseObj: {
            jingque: true,
            jigao: true,
            jichao: true,
            xjjiaodu: true,
            bgjiaodu: true,
            bgliangdu: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "lianpai",
          actionTypeLabel: "连拍",
          actionTypeIcon: "tubiao_hengxianglianpai-40",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            jingque: true,
            jigao: true,
            jichao: true,
            xjjiaodu: true,
            bgjiaodu: true,
            bgliangdu: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "fangdian",
          actionTypeLabel: "局部放电检测",
          actionTypeIcon: "tubiao_fangdianjiance",
          canUsePresetPoint: false,
          locationPoseObj: {
            jingque: true,
            jigao: true,
            jichao: true,
          },
        },
        {
          actionTypeValue: "shouwang",
          actionTypeLabel: "守望",
          actionTypeIcon: "shouwang",
          canUsePresetPoint: false,
          locationPoseObj: {
            xingzou: true,
            jingque: true,
            jigao: true,
            jichao: true,
            xjjiaodu: true,
            bgjiaodu: true,
            bgliangdu: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
      ],
    },
    //固定可见光摄像头
    {
      devicesTypeValue: "3",
      actionTypeOption: [
        {
          actionTypeValue: "zhuapai",
          actionTypeLabel: "可见光抓拍",
          actionTypeIcon: "tubiao_kejianguangzhuapai-42",
          canUsePresetPoint: true,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "biaoji",
          actionTypeLabel: "表计识别",
          actionTypeIcon: "kejianguangshibie",
          canUsePresetPoint: true,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "lianpai",
          actionTypeLabel: "连拍",
          actionTypeIcon: "tubiao_hengxianglianpai-40",
          canUsePresetPoint: false,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "shouwang",
          actionTypeLabel: "守望",
          actionTypeIcon: "shouwang",
          canUsePresetPoint: true,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
      ],
    },
    //固定双光摄像头
    {
      devicesTypeValue: "4",
      canUsePresetPoint: true,
      actionTypeOption: [
        {
          actionTypeValue: "zhuapai",
          actionTypeLabel: "可见光抓拍",
          actionTypeIcon: "tubiao_kejianguangzhuapai-42",
          canUsePresetPoint: true,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "hongwai",
          actionTypeLabel: "红外测温",
          actionTypeIcon: "redtemp",
          canUsePresetPoint: false,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "biaoji",
          actionTypeLabel: "表计识别",
          actionTypeIcon: "kejianguangshibie",
          canUsePresetPoint: true,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "lianpai",
          actionTypeLabel: "连拍",
          actionTypeIcon: "tubiao_hengxianglianpai-40",
          canUsePresetPoint: false,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
        {
          actionTypeValue: "shouwang",
          actionTypeLabel: "守望",
          actionTypeIcon: "shouwang",
          canUsePresetPoint: true,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            bianjiao: true,
            bianbei: true,
            huamian: true,
          },
        },
      ],
    },
    //固定红外摄像头
    {
      devicesTypeValue: "5",
      canUsePresetPoint: false,
      actionTypeOption: [
        {
          actionTypeValue: "hongwai",
          actionTypeLabel: "红外测温",
          actionTypeIcon: "redtemp ",
          canUsePresetPoint: false,
          locationPoseObj: {
            shuiping: true,
            chuizhi: true,
            huamian: true,
          },
        },
      ],
    },
  ];

  return {
    list,
  };
}
